### ISSUE TITLE
Italic, small-caps, bold etc. font

### ISSUE THREAD

**Issue by dy** [hughsk/font-atlas#1]
Seems that right now only font-size and font-family are supported.

Probably having normal CSS `font` property or object would be more useful than it is now. There are [css-font](https://github.com/dy/css-font) or [parse-css-font](https://npmjs.org/parse-css-font) packages for that purpose.

@hughsk would you consider a PR?

**Comment by hughsk** [comment]
Will add you to the repo/package! Otherwise I might miss it :')

**Comment by dy** [comment]
Ok, I can normalize the API of [font-atlas-sdf](https://github.com/dy/font-atlas-sdf) as well then.

**Comment by dy** [comment]
Done in 2.0.0
